### ISSUE TITLE
A pull request triggers twice the same pipeline

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/tower_utilities#16]
It's not a big issue as long as the pipeline is short, but starts to be annoying when the pipeline takes more time.

I have no experience with GitHub Actions and only slightly more with .travis.yml but the way we solved this issue on another project was to only trigger on commits/branches/tags having specific names (e.g. master/devel, tags looking like release numbers, and branches ending with '_', useful especially when you just want to test the pipeline).

**Comment by sean-m-sullivan** [comment]
We would be up for selective trigger, I think a lot of us are new to this, but the doing a push/pull trigger at the same time is something that wasn't happening till recently.

**Comment by Tompage1994** [comment]
Yeah, @ericzolf we haven't been pushing branches to this repo in general (partly due to permissions), and instead working off of forks. I guess you have permissions so you were able to create other branches.

I assume that is the main cause, and as that isnt the usual flow then we can probably ignore this (unless there is a simple fix which I'm not sure about)

**Comment by ericzolf** [comment]
There should be an easy fix according to my experience with Travis, which isn't very different from GitHub actions, I'll have a look once I find time. It went down the priority list now that I know, I might be the only one impacted :stuck_out_tongue_winking_eye:

**Comment by Tompage1994** [comment]
Don't think this is really an issue anymore
