### ISSUE TITLE
rename to controller_utilities

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/tower_utilities#67]
rename the repo and update links to controller_utilities

**Comment by sean-m-sullivan** [comment]
Done, But now we have to check our links and docs.

**Comment by sean-m-sullivan** [comment]
And now that I think of it, aap_utilties???

**Comment by djdanielsson** [comment]
yea that is true, but then i kinda want to rename all the roles and remove the extra aap there

**Comment by ericzolf** [comment]
Two points from me:
1. yes, it should be aap_utilities because we deploy everything, not only the controller.
2. during one of the last CoP meetings, we decided that prefixing the role was wishable as long as it remains short (which aap is). See https://docs.google.com/document/d/1qzRVikXbgVXDtNxi2J4IL5fHclClzcOIxsrB7X-yIuc/edit?skip_itp2_check=true#heading=h.v9ijp8rfy01r (@mophahr still has a task to bring it into the good practices).

**Comment by sean-m-sullivan** [comment]
This has been done, closing
